import assert from "node:assert/strict";
import { readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";
import type { AssistantMessage } from "@earendil-works/pi-ai";
import {
	createAgentSession,
	SessionManager,
	SettingsManager,
	type AgentSession,
} from "@earendil-works/pi-coding-agent";
// @ts-ignore JavaScript verification module without generated declarations.
import { makeFixture, smokeExtensionFromExtracted, verifyPackage } from "../scripts/verify-package.mjs";

const packageRoot = dirname(dirname(fileURLToPath(import.meta.url)));

type Component = { handleInput?: (data: string) => void };

function tuiUI(
	initialInputs: string[],
	notifications: string[] = [],
	afterSelection?: () => void,
) {
	let inputs = initialInputs;
	let customCalls = 0;
	const ui = {
		select: async () => undefined,
		confirm: async () => false,
		input: async () => undefined,
		notify: (message: string) => notifications.push(message),
		onTerminalInput: () => () => undefined,
		setStatus: () => undefined,
		setWorkingMessage: () => undefined,
		setWorkingVisible: () => undefined,
		setWorkingIndicator: () => undefined,
		setHiddenThinkingLabel: () => undefined,
		setWidget: () => undefined,
		setFooter: () => undefined,
		setHeader: () => undefined,
		setTitle: () => undefined,
		custom: async (factory: any) => {
			customCalls++;
			let result: unknown;
			const component = (await factory({}, {}, {}, (value: unknown) => {
				result = value;
			})) as Component;
			for (const input of inputs) component.handleInput?.(input);
			if (result !== undefined) afterSelection?.();
			return result;
		},
	};
	return {
		uiContext: ui as any,
		customCalls: () => customCalls,
		setInputs: (nextInputs: string[]) => { inputs = nextInputs; },
	};
}

async function runCommand(session: AgentSession, args: string, ui?: ReturnType<typeof tuiUI>) {
	if (ui) await session.bindExtensions({ mode: "tui", uiContext: ui.uiContext });
	const command = session.extensionRunner.getCommand("session-only-model");
	assert.ok(command);
	await command.handler(args, session.extensionRunner.createCommandContext());
}

function temporaryAssistant(model = "m2"): AssistantMessage {
	return {
		role: "assistant",
		content: [{ type: "text", text: "generated by temporary model" }],
		api: "openai-completions",
		provider: "test",
		model,
		usage: {
			input: 1,
			output: 1,
			cacheRead: 0,
			cacheWrite: 0,
			totalTokens: 2,
			cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, total: 0 },
		},
		stopReason: "stop",
		timestamp: Date.now(),
	};
}

test("picker applies one confirmed model/thinking pair while a normal model change remains persistent", async () => {
	const fixture = await makeFixture({ repoRoot: packageRoot });
	let session: AgentSession | undefined;
	try {
		const settingsManager = SettingsManager.create(fixture.cwd, fixture.agentDir);
		const sessionManager = SessionManager.inMemory(fixture.cwd);
		({ session } = await createAgentSession({
			cwd: fixture.cwd,
			agentDir: fixture.agentDir,
			modelRuntime: fixture.modelRuntime,
			settingsManager,
			sessionManager,
			noTools: "all",
		}));
		assert.equal(session.thinkingLevel, "medium");
		const ui = tuiUI(["m2", "\r", "\r"]);
		await runCommand(session, "", ui);
		await settingsManager.flush();
		assert.equal(session.model?.id, "m2");
		assert.equal(session.thinkingLevel, "minimal");
		assert.equal(ui.customCalls(), 1);
		assert.deepEqual(JSON.parse(await readFile(join(fixture.agentDir, "settings.json"), "utf8")), {
			defaultProvider: "test",
			defaultModel: "m1",
			defaultThinkingLevel: "medium",
		});
		assert.equal(sessionManager.getEntries().some((entry) => entry.type === "model_change" && entry.modelId === "m2"), false);
		assert.equal(sessionManager.getEntries().some((entry) => entry.type === "thinking_level_change" && entry.thinkingLevel === "minimal"), false);

		ui.setInputs(["\r", "\r"]);
		await runCommand(session, "");
		assert.equal(session.model?.id, "m2");
		assert.equal(session.thinkingLevel, "minimal");

		const setModel = session!.setModel.bind(session!) as unknown as (
			model: Parameters<AgentSession["setModel"]>[0],
			options?: { persist?: boolean },
		) => Promise<void>;
		await setModel(fixture.modelRuntime.getModel("test", "m3")!, { persist: true });
		await settingsManager.flush();
		assert.equal(session.model?.id, "m3");
		assert.equal(sessionManager.getEntries().some((entry) => entry.type === "model_change" && entry.modelId === "m3"), true);
		assert.equal(JSON.parse(await readFile(join(fixture.agentDir, "settings.json"), "utf8")).defaultModel, "m3");
		// A normal /model change must not be recorded into the session-only recency history (R6).
		assert.deepEqual(
			JSON.parse(await readFile(join(fixture.agentDir, "recent-session-models.json"), "utf8")),
			[{ provider: "test", id: "m2" }],
		);
	} finally {
		await fixture.cleanup(session);
	}
});

test("session-only model stays ahead after tree navigation", async () => {
	const fixture = await makeFixture({ repoRoot: packageRoot });
	let session: AgentSession | undefined;
	try {
		const settingsManager = SettingsManager.create(fixture.cwd, fixture.agentDir);
		const sessionManager = SessionManager.inMemory(fixture.cwd);
		({ session } = await createAgentSession({
			cwd: fixture.cwd,
			agentDir: fixture.agentDir,
			modelRuntime: fixture.modelRuntime,
			settingsManager,
			sessionManager,
			noTools: "all",
		}));
		// Select m2 through /session-only-model so it is recorded as recently used.
		await runCommand(session, "", tuiUI(["m2", "\r", "\r"]));
		assert.equal(session.model?.id, "m2");

		// Navigating to an older transcript point must not drop the persisted
		// recency; the picker still promotes m2 from the history file (R4).
		const modelChangeId = sessionManager.appendModelChange("test", "m3");
		sessionManager.appendMessage(temporaryAssistant());
		await session.navigateTree(modelChangeId, { summarize: false });
		await runCommand(session, "", tuiUI(["\r", "\r"]));
		assert.equal(session.model?.id, "m2");
	} finally {
		await fixture.cleanup(session);
	}

});

test("picker applies off for a non-reasoning model through setModel normalization", async () => {
	const fixture = await makeFixture({ repoRoot: packageRoot });
	let session: AgentSession | undefined;
	try {
		fixture.modelRuntime.registerProvider("no-reasoning", {
			baseUrl: "https://example.invalid/v1",
			apiKey: "dummy",
			api: "openai-completions",
			models: [{
				id: "m-off",
				name: "m-off",
				reasoning: false,
				input: ["text"],
				cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
				contextWindow: 10_000,
				maxTokens: 1_000,
			}],
		});
		const settingsManager = SettingsManager.create(fixture.cwd, fixture.agentDir);
		const sessionManager = SessionManager.inMemory(fixture.cwd);
		({ session } = await createAgentSession({
			cwd: fixture.cwd,
			agentDir: fixture.agentDir,
			modelRuntime: fixture.modelRuntime,
			settingsManager,
			sessionManager,
			noTools: "all",
		}));
		assert.equal(session.thinkingLevel, "medium");
		await runCommand(session, "", tuiUI(["no-reasoning/m-off", "\r", "\r"]));
		assert.equal(session.model?.id, "m-off");
		assert.equal(session.thinkingLevel, "off");
	} finally {
		await fixture.cleanup(session);
	}
});

test("cancelling either picker stage leaves the current session unchanged", async () => {
	const fixture = await makeFixture({ repoRoot: packageRoot });
	let session: AgentSession | undefined;
	try {
		const settingsManager = SettingsManager.create(fixture.cwd, fixture.agentDir);
		const sessionManager = SessionManager.inMemory(fixture.cwd);
		({ session } = await createAgentSession({
			cwd: fixture.cwd,
			agentDir: fixture.agentDir,
			modelRuntime: fixture.modelRuntime,
			settingsManager,
			sessionManager,
			noTools: "all",
		}));
		const ui = tuiUI(["\u001b"]);
		await runCommand(session, "", ui);
		assert.equal(session.model?.id, "m1");
		assert.equal(session.thinkingLevel, "medium");
		ui.setInputs(["\r", "\u001b"]);
		await runCommand(session, "");
		assert.equal(session.model?.id, "m1");
		assert.equal(session.thinkingLevel, "medium");
		assert.equal(sessionManager.getEntries().some((entry) => entry.type === "model_change" && entry.modelId === "m2"), false);
	} finally {
		await fixture.cleanup(session);
	}
});

test("non-TUI and unsupported input report without changing session state", async () => {
	const fixture = await makeFixture({ repoRoot: packageRoot });
	let session: AgentSession | undefined;
	try {
		const settingsManager = SettingsManager.create(fixture.cwd, fixture.agentDir);
		const sessionManager = SessionManager.inMemory(fixture.cwd);
		({ session } = await createAgentSession({
			cwd: fixture.cwd,
			agentDir: fixture.agentDir,
			modelRuntime: fixture.modelRuntime,
			settingsManager,
			sessionManager,
			noTools: "all",
		}));
		const notifications: string[] = [];
		const printUI = tuiUI([], notifications);
		await session.bindExtensions({ mode: "print", uiContext: printUI.uiContext });
		await runCommand(session, "", undefined);
		await runCommand(session, "test/m2 --thinking high", undefined);
		await runCommand(session, "status", undefined);
		assert.equal(session.model?.id, "m1");
		assert.equal(session.thinkingLevel, "medium");
		assert.equal(notifications.some((message) => message.includes("only available in TUI")), true);
		assert.equal(notifications.some((message) => message.includes("unsupported")), true);
	} finally {
		await fixture.cleanup(session);
	}
});

test("reset restores the baseline and an unauthenticated apply leaves the override inactive", async () => {
	const fixture = await makeFixture({ repoRoot: packageRoot });
	let session: AgentSession | undefined;
	try {
		fixture.modelRuntime.registerProvider("unauth", {
			baseUrl: "https://example.invalid/v1",
			api: "openai-completions",
			apiKey: "dummy",
			models: [{ id: "m4", name: "m4", reasoning: true, input: ["text"], cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 10_000, maxTokens: 1_000 }],
		});
		const settingsManager = SettingsManager.create(fixture.cwd, fixture.agentDir);
		const sessionManager = SessionManager.inMemory(fixture.cwd);
		({ session } = await createAgentSession({
			cwd: fixture.cwd,
			agentDir: fixture.agentDir,
			modelRuntime: fixture.modelRuntime,
			settingsManager,
			sessionManager,
			noTools: "all",
		}));
		const notifications: string[] = [];
		const ui = tuiUI(["m2", "\r", "\r"], notifications);
		await runCommand(session, "", ui);
		assert.equal(session.model?.id, "m2");
		ui.setInputs([]);
		await runCommand(session, "reset");
		assert.equal(session.model?.id, "m1");
		assert.equal(session.thinkingLevel, "medium");
		const failureUI = tuiUI(["unauth", "\r", "\r"], notifications, () => fixture.modelRuntime.unregisterProvider("unauth"));
		await runCommand(session, "", failureUI);
		assert.equal(session.model?.id, "m1");
		assert.equal(session.thinkingLevel, "medium");
		assert.equal(notifications.some((message) => /authentication|auth/i.test(message)), true);
	} finally {
		await fixture.cleanup(session);
	}
});

test("packed artifact loads through Pi integration fixture", async () => {
	const verified = await verifyPackage({ packageRoot, keepWorkDir: true });
	try {
		await smokeExtensionFromExtracted(verified.extractedDir, packageRoot);
	} finally {
		if (verified.workDir) await rm(verified.workDir, { recursive: true, force: true });
	}
});

test("a transcript produced by the temporary model resumes from settings defaults", async () => {
	const fixture = await makeFixture({ repoRoot: packageRoot });
	let currentSession: AgentSession | undefined;
	try {
		const sessionManager = SessionManager.inMemory(fixture.cwd);
		let settingsManager = SettingsManager.create(fixture.cwd, fixture.agentDir);
		const first = await createAgentSession({
			cwd: fixture.cwd,
			agentDir: fixture.agentDir,
			modelRuntime: fixture.modelRuntime,
			settingsManager,
			sessionManager,
			noTools: "all",
		});
		currentSession = first.session;
		await runCommand(currentSession, "", tuiUI(["m2", "\r", "\r"]));
		sessionManager.appendMessage(temporaryAssistant());
		assert.deepEqual(sessionManager.buildSessionContext().model, { provider: "test", modelId: "m2" });

		await currentSession.extensionRunner.emit({ type: "session_shutdown", reason: "quit" });
		currentSession.dispose();
		currentSession = undefined;

		settingsManager = SettingsManager.create(fixture.cwd, fixture.agentDir);
		const resumed = await createAgentSession({
			cwd: fixture.cwd,
			agentDir: fixture.agentDir,
			modelRuntime: fixture.modelRuntime,
			settingsManager,
			sessionManager,
			noTools: "all",
		});
		currentSession = resumed.session;
		const resumeUi = tuiUI(["\r", "\r"]);
		await currentSession.bindExtensions({ mode: "tui", uiContext: resumeUi.uiContext });
		assert.equal(currentSession.model?.id, "m1");
		assert.equal(currentSession.thinkingLevel, "medium");
		await runCommand(currentSession, "");
		assert.equal(currentSession.model?.id, "m2");
		assert.equal(currentSession.thinkingLevel, "minimal");
	} finally {
		await fixture.cleanup(currentSession);
	}
});

test("recently used model persists across sessions", async () => {
	const fixture = await makeFixture({ repoRoot: packageRoot });
	let firstSession: AgentSession | undefined;
	let secondSession: AgentSession | undefined;
	try {
		const settingsManager = SettingsManager.create(fixture.cwd, fixture.agentDir);
		const firstManager = SessionManager.inMemory(fixture.cwd);
		({ session: firstSession } = await createAgentSession({
			cwd: fixture.cwd,
			agentDir: fixture.agentDir,
			modelRuntime: fixture.modelRuntime,
			settingsManager,
			sessionManager: firstManager,
			noTools: "all",
		}));
		await runCommand(firstSession, "", tuiUI(["m2", "\r", "\r"]));
		assert.equal(firstSession.model?.id, "m2");

		// A fresh session on the same agent dir shares the persisted history
		// (across sessions and Pi restarts), so m2 is still promoted (R2, R4).
		await firstSession.extensionRunner.emit({ type: "session_shutdown", reason: "quit" });
		firstSession.dispose();
		firstSession = undefined;
		const secondManager = SessionManager.inMemory(fixture.cwd);
		({ session: secondSession } = await createAgentSession({
			cwd: fixture.cwd,
			agentDir: fixture.agentDir,
			modelRuntime: fixture.modelRuntime,
			settingsManager,
			sessionManager: secondManager,
			noTools: "all",
		}));
		await runCommand(secondSession, "", tuiUI(["\r", "\r"]));
		assert.equal(secondSession.model?.id, "m2");
	} finally {
		if (secondSession) {
			await secondSession.extensionRunner.emit({ type: "session_shutdown", reason: "quit" });
			secondSession.dispose();
		}
		await fixture.cleanup(firstSession ?? secondSession);
	}

});

test("hot reload keeps the temporary model ahead of older transcript history", async () => {
	const fixture = await makeFixture({ repoRoot: packageRoot });
	let session: AgentSession | undefined;
	try {
		const settingsManager = SettingsManager.create(fixture.cwd, fixture.agentDir);
		const sessionManager = SessionManager.inMemory(fixture.cwd);
		({ session } = await createAgentSession({
			cwd: fixture.cwd,
			agentDir: fixture.agentDir,
			modelRuntime: fixture.modelRuntime,
			settingsManager,
			sessionManager,
			noTools: "all",
		}));
		// Older transcript history generated with a different model.
		sessionManager.appendMessage(temporaryAssistant("m1"));
		const ui = tuiUI(["m2", "\r", "\r"]);
		await runCommand(session, "", ui);
		assert.equal(session.model?.id, "m2");

		// Reload rebuilds the runtime, but the recent model is read back from the
		// persisted history file, so m2 stays ahead of the older transcript.
		await session.reload();
		ui.setInputs(["\r", "\r"]);
		await runCommand(session, "");
		assert.equal(session.model?.id, "m2");
	} finally {
		await fixture.cleanup(session);
	}
});

test("canceling the picker leaves the persisted history unchanged", async () => {
	const fixture = await makeFixture({ repoRoot: packageRoot });
	let session: AgentSession | undefined;
	try {
		const settingsManager = SettingsManager.create(fixture.cwd, fixture.agentDir);
		const sessionManager = SessionManager.inMemory(fixture.cwd);
		({ session } = await createAgentSession({
			cwd: fixture.cwd,
			agentDir: fixture.agentDir,
			modelRuntime: fixture.modelRuntime,
			settingsManager,
			sessionManager,
			noTools: "all",
		}));
		await runCommand(session, "", tuiUI(["m2", "\r", "\r"]));
		assert.equal(session.model?.id, "m2");
		const historyPath = join(fixture.agentDir, "recent-session-models.json");
		assert.deepEqual(JSON.parse(await readFile(historyPath, "utf8")), [{ provider: "test", id: "m2" }]);
		// Canceling the model stage returns no selection, so nothing is recorded (R7).
		await runCommand(session, "", tuiUI(["\u001b"]));
		assert.equal(session.model?.id, "m2");
		assert.deepEqual(JSON.parse(await readFile(historyPath, "utf8")), [{ provider: "test", id: "m2" }]);
	} finally {
		await fixture.cleanup(session);
	}
});

test("a failed apply does not write to the persisted history", async () => {
	const fixture = await makeFixture({ repoRoot: packageRoot });
	let session: AgentSession | undefined;
	try {
		fixture.modelRuntime.registerProvider("unauth", {
			baseUrl: "https://example.invalid/v1",
			api: "openai-completions",
			apiKey: "dummy",
			models: [{ id: "m4", name: "m4", reasoning: true, input: ["text"], cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 10_000, maxTokens: 1_000 }],
		});
		const settingsManager = SettingsManager.create(fixture.cwd, fixture.agentDir);
		const sessionManager = SessionManager.inMemory(fixture.cwd);
		({ session } = await createAgentSession({
			cwd: fixture.cwd,
			agentDir: fixture.agentDir,
			modelRuntime: fixture.modelRuntime,
			settingsManager,
			sessionManager,
			noTools: "all",
		}));
		await runCommand(session, "", tuiUI(["m2", "\r", "\r"]));
		const historyPath = join(fixture.agentDir, "recent-session-models.json");
		assert.deepEqual(JSON.parse(await readFile(historyPath, "utf8")), [{ provider: "test", id: "m2" }]);
		// An unauthenticated apply fails; the selection is discarded, not recorded (R7).
		const notifications: string[] = [];
		const failureUI = tuiUI(["unauth", "\r", "\r"], notifications, () => fixture.modelRuntime.unregisterProvider("unauth"));
		await runCommand(session, "", failureUI);
		assert.equal(notifications.some((message) => /authentication|auth/i.test(message)), true);
		assert.equal(session.model?.id, "m2");
		assert.deepEqual(JSON.parse(await readFile(historyPath, "utf8")), [{ provider: "test", id: "m2" }]);
	} finally {
		await fixture.cleanup(session);
	}
});

test("picker opens when the recent history file is corrupt", async () => {
	const fixture = await makeFixture({ repoRoot: packageRoot });
	let session: AgentSession | undefined;
	try {
		const settingsManager = SettingsManager.create(fixture.cwd, fixture.agentDir);
		const sessionManager = SessionManager.inMemory(fixture.cwd);
		({ session } = await createAgentSession({
			cwd: fixture.cwd,
			agentDir: fixture.agentDir,
			modelRuntime: fixture.modelRuntime,
			settingsManager,
			sessionManager,
			noTools: "all",
		}));
		// A corrupt history file must not crash the picker; it opens with no promotion (R7).
		await writeFile(join(fixture.agentDir, "recent-session-models.json"), "{ not valid json", "utf8");
		await runCommand(session, "", tuiUI(["m2", "\r", "\r"]));
		assert.equal(session.model?.id, "m2");
	} finally {
		await fixture.cleanup(session);
	}
});
