import assert from "node:assert/strict";
import { readFile, rm } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";
import type { AssistantMessage } from "@earendil-works/pi-ai";
import {
	createAgentSession,
	SessionManager,
	SettingsManager,
	type AgentSession,
} from "@earendil-works/pi-coding-agent";
// @ts-ignore JavaScript verification module without generated declarations.
import { makeFixture, smokeExtensionFromExtracted, verifyPackage } from "../scripts/verify-package.mjs";

const packageRoot = dirname(dirname(fileURLToPath(import.meta.url)));

function temporaryAssistant(): AssistantMessage {
	return {
		role: "assistant",
		content: [{ type: "text", text: "generated by temporary model" }],
		api: "openai-completions",
		provider: "test",
		model: "m2",
		usage: {
			input: 1,
			output: 1,
			cacheRead: 0,
			cacheWrite: 0,
			totalTokens: 2,
			cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, total: 0 },
		},
		stopReason: "stop",
		timestamp: Date.now(),
	};
}

test("/session-only-model is ephemeral while a normal model change remains persistent", async () => {
	const fixture = await makeFixture({ repoRoot: packageRoot });
	let session: AgentSession | undefined;
	try {
		const settingsManager = SettingsManager.create(fixture.cwd, fixture.agentDir);
		const sessionManager = SessionManager.inMemory(fixture.cwd);
		({ session } = await createAgentSession({
			cwd: fixture.cwd,
			agentDir: fixture.agentDir,
			modelRuntime: fixture.modelRuntime,
			settingsManager,
			sessionManager,
			noTools: "all",
		}));
		await session.bindExtensions({ mode: "print" });

		await session.prompt("/session-only-model test/m2 --thinking high");
		await settingsManager.flush();
		assert.equal(session.model?.id, "m2");
		assert.equal(session.thinkingLevel, "high");
		assert.deepEqual(JSON.parse(await readFile(join(fixture.agentDir, "settings.json"), "utf8")), {
			defaultProvider: "test",
			defaultModel: "m1",
			defaultThinkingLevel: "medium",
		});
		assert.equal(
			sessionManager.getEntries().some((entry) => entry.type === "model_change" && entry.modelId === "m2"),
			false,
		);
		assert.equal(
			sessionManager.getEntries().some((entry) => entry.type === "thinking_level_change" && entry.thinkingLevel === "high"),
			false,
		);

		await session.setModel(fixture.modelRuntime.getModel("test", "m3")!);
		await settingsManager.flush();
		assert.equal(session.model?.id, "m3");
		assert.equal(
			sessionManager.getEntries().some((entry) => entry.type === "model_change" && entry.modelId === "m3"),
			true,
		);
		assert.equal(
			JSON.parse(await readFile(join(fixture.agentDir, "settings.json"), "utf8")).defaultModel,
			"m3",
		);
	} finally {
		await fixture.cleanup(session);
	}
});

test("packed artifact loads through Pi integration fixture", async () => {
	const verified = await verifyPackage({ packageRoot, keepWorkDir: true });
	try {
		await smokeExtensionFromExtracted(verified.extractedDir, packageRoot);
	} finally {
		if (verified.workDir) {
			await rm(verified.workDir, { recursive: true, force: true });
		}
	}
});

test("a transcript produced by the temporary model resumes from settings defaults", async () => {
	const fixture = await makeFixture({ repoRoot: packageRoot });
	let currentSession: AgentSession | undefined;
	try {
		const sessionManager = SessionManager.inMemory(fixture.cwd);
		let settingsManager = SettingsManager.create(fixture.cwd, fixture.agentDir);
		const first = await createAgentSession({
			cwd: fixture.cwd,
			agentDir: fixture.agentDir,
			modelRuntime: fixture.modelRuntime,
			settingsManager,
			sessionManager,
			noTools: "all",
		});
		currentSession = first.session;
		await currentSession.bindExtensions({ mode: "print" });
		await currentSession.prompt("/session-only-model test/m2 --thinking high");
		sessionManager.appendMessage(temporaryAssistant());
		assert.deepEqual(sessionManager.buildSessionContext().model, { provider: "test", modelId: "m2" });

		await currentSession.extensionRunner.emit({ type: "session_shutdown", reason: "quit" });
		currentSession.dispose();
		currentSession = undefined;

		settingsManager = SettingsManager.create(fixture.cwd, fixture.agentDir);
		const resumed = await createAgentSession({
			cwd: fixture.cwd,
			agentDir: fixture.agentDir,
			modelRuntime: fixture.modelRuntime,
			settingsManager,
			sessionManager,
			noTools: "all",
		});
		currentSession = resumed.session;
		await currentSession.bindExtensions({ mode: "print" });
		assert.equal(currentSession.model?.id, "m1");
		assert.equal(currentSession.thinkingLevel, "medium");
	} finally {
		await fixture.cleanup(currentSession);
	}
});
